from enum import Enum

class ReasonCode(str, Enum):
    WEATHER_HEAVY_RAIN = 'WEATHER_HEAVY_RAIN'
    WEATHER_LOW_VISIBILITY = 'WEATHER_LOW_VISIBILITY'
    WEATHER_STRONG_WIND = 'WEATHER_STRONG_WIND'
    WEATHER_FOG = 'WEATHER_FOG'
    GEOFENCE_AHEAD = 'GEOFENCE_AHEAD'
    IN_GEOFENCE_FORBIDDEN_ZONE = 'IN_GEOFENCE_FORBIDDEN_ZONE'
    IN_GEOFENCE_SLOW_ZONE = 'IN_GEOFENCE_SLOW_ZONE'
    IN_GEOFENCE_CAUTION_ZONE = 'IN_GEOFENCE_CAUTION_ZONE'
    NETWORK_POOR = 'NETWORK_POOR'
    NETWORK_LOST = 'NETWORK_LOST'
    MULTI_FACTOR_RISK = 'MULTI_FACTOR_RISK'
